### ISSUE TITLE
Cronjob Support

### ISSUE THREAD

**Issue by qgervacio** [k8s-at-home/library-charts#110]
# Details

**Helm chart name:** chartlib

**Describe the solution you'd like:** Support for CronJob template

**Anything else you would like to add:** I think NetworkPolicy should be treated as a first class citizen not just a addons/vpn

**Additional Information:**

**Comment by onedr0p** [comment]
I am not convinced adding a CronJob controller to the common chart will be worth it IMO. `CronJob` specs are pretty different than `Deployments`, `StatefulSets` and `DaemonSets` and are generally pretty easy to write with little code. For example https://github.com/onedr0p/home-cluster/tree/main/cluster/apps/monitoring/uptimerobot-heartbeat

I don't have much to say about `NetworkPolicy` but maybe that is useful? I am not sure.

**Comment by bjw-s** [comment]
I am inclined to agree with @onedr0p on this. The idea behind the common chart is to be a library that is useful to a large part of our charts. I think only a very limited number of charts would benefit from having direct support for CronJob and/or NetworkPolicy objects. 

NetworkPolicy objects are also very user-specific, so I would think the amount of yaml that would be written in the `values.yaml` file will end up pretty similar to just adding a NetworkPolicy manifest manually. But I must admit that I am not super well versed in them yet, so I may be completely wrong there 😛

**Comment by qgervacio** [comment]
I think it's a good idea to support `CronJob` and `NetworkPolicy` natively because it will only be a matter of time when someone would need it; that time is now and that someone is me 😅

I don't think it's an option for me to look for another chart library that has a `NetworkPolicy` implementation which I will then attempt to coexist with `commons`.

For `NetworkPolicy` we use it in **all** projects. I noticed there's an `addons/vpn/_networkpolicy.tpl` which I was hesitant to use hence I had to come up with the following. I followed the implementation of `common.ingress`

```
networkpolicy:
  aaa:
    enabled: true
    podSelector:
      matchExpressions:
      - {key: _some-key-here_, operator: In, values: ["_some-val-here_"] }
    egress:
    - ports:
      - port: _some-port-here_
        protocol: TCP
      to:
      - ipBlock:
          cidr: _some-cicdr-here_
  bbb: ...
  ccc: ...
```
