### ISSUE TITLE
[common] Treat custom service ports as enabled by default

### ISSUE THREAD

**Issue by MurzNN** [k8s-at-home/library-charts#124]
# Details
When I fill this structure for service:
```yaml
service:
  main:
    ports:
      appservice:
        port: 9993
      webhook:
        port: 9000
      metrics:
        port: 9002
```
as result common library renders only single empty port in Service, instead of list of all described ports:
```yaml
spec:
  type: ClusterIP
  ports:
  - port: 
    targetPort: http
    protocol: TCP
    name: http
```
And to make desired port configuration I need to explicitly disable default `http` port and enable all others, like this:
```yaml
service:
  main:
    ports:
      http:
        enabled: false
      appservice:
        enabled: true
        port: 9993
      webhook:
        enabled: true
        port: 9000
      metrics:
        enabled: true
        port: 9002
```

**Helm chart name:** common

**Describe the solution you'd like:** I suggest to treat custom service ports as enabled by default, to not write "enabled = true" on each new port, and disable default `http` port if no value is specified.
