### ISSUE TITLE
externalTrafficPolicy is valid for type: NodePort

### ISSUE THREAD

**Issue by mleklund** [k8s-at-home/library-charts#125]
# Details

common-4.3.0

I set the externalTrafficPolicy to Local for a chart using common, and it was ignored

```
service:
  https:
    enabled: true
    primary: true
    externalTrafficPolicy: "Local"
    type: NodePort
    ports:
      https:
        enabled: true
        port: 443
      http:
        enabled: false
```

externalTrafficPolicy on the returned service should be set to local
