### ISSUE TITLE
persistence.name does not apply fullname for configMap names

### ISSUE THREAD

**Issue by thiemok** [k8s-at-home/library-charts#146]
# Details

**Helm chart name and version:**
unifi: 4.6.1
common: 4.3.0

**What steps did you take and what happened:**

Adding a custom persistence configuration of type `configMap`  does not apply `common.name.fullname` to the provided config map name, while a configMap created via `Values.configmap` does prepend the fullname to the created configMap.
Many charts apply manual workarounds to this problem ([example1](https://github.com/k8s-at-home/charts/blob/5573907216d57a3232b4d7343ab7e61a896e8cb5/charts/stable/vikunja/templates/common.yaml#L14), [example2](https://github.com/k8s-at-home/charts/blob/f02beeb9f03df63b798b440b6cae4dfced1379e9/charts/stable/privatebin/templates/common.yaml#L11))
However there seems to be no documented way to achieve the same result just in a `Values.yaml` file

**Relevant Helm values:**

[Abbreviated example values.yaml](https://pastebin.com/LjNCFS7v)

**What did you expect to happen:**
* A configMap named `unifi-site.config` is generated
* The main pod recieves the following volume:
```yaml
  - configMap:
      defaultMode: 420
      items:
      - key: config.gateway.json
        path: config.gateway.json
      name: unifi-site-config #The actual value being generated here is currently site-config
    name: site-config
```

NOTE: The `site-config` configMap is an additional one I#m trying to add and not originally part of the `unifi` chart
