### ISSUE TITLE
ability to add a ca-bundle via common library

### ISSUE THREAD

**Issue by lknite** [k8s-at-home/library-charts#148]
# Details

common library:
https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/values.yaml

**Describe the solution you'd like:**

There are several ways projects have accomplished this.  Open to ideas.  The last way I accomplished this was to create secret with one item "ca.crt" then mount it in such a way as to overwrite things.

```
  extraVolumeMounts:
  - name: certificate
    mountPath: /etc/ssl/certs/ca.crt # your self-signed CA part inside the secret
    subPath: ca.crt
  extraVolumes:
  - name: certificate
    secret:
    secretName: ca-bundle
    defaultMode: 420
```

Though something more specific like specify your tls value here and it will be added in the right place internally would be nice.  This would be helpful with a container like keycloak, which uses python internally, and needs the ca-bundle in a different location.  With a common library you could always specify in the same way and it would end up in the right place everytime.

**Anything else you would like to add:**

Just allowing extra volume mounts would work.  I could use them to overwrite the existing ca.crt or mount and then use an init container to update-ca-certificates.  Though, if a container required the ca-bundle in a different location one would have to figure out where it needs to go, which can be difficult.

**Additional Information:**

A use case for this is using heimdall in an environment which rewrites https for monitoring purposes, the local ca needs to be trusted otherwise https requests come back with errors similar to self-signed certificate detected.

**Comment by lknite** [comment]
Figured out a way to make it work with the existing common library:
https://github.com/k8s-at-home/docs/blob/main/docs/our-helm-charts/common-library-storage.md

```
  persistence:
    ca-bundle:
      enabled: true
      type: custom
      volumeSpec:
        secret:
          secretName: ca-bundle
          defaultMode: 420
      subPath:
        - path: ca.crt
          mountPath: /etc/ssl/certs/ca.crt
```
