### ISSUE TITLE
typo in HPA annotations

### ISSUE THREAD

**Issue by disconn3ct** [k8s-at-home/library-charts#158]
# Details

**Helm chart name and version:** Common 4.4.0

**What steps did you take and what happened:** HPA is enabled. CICD accepted a minor revision of a leaf chart (searx) and failed with a templating error: `Helm upgrade failed: template: searx/templates/common.yaml:89:3: executing "searx/templates/common.yaml" at <include "common.all" .>: error calling include: template: searx/charts/common/templates/_all.tpl:49:5: executing "common.all" at <include "common.classes.hpa" .>: error calling include: template: searx/charts/common/templates/classes/_HorizontalPodAutoscaler.tpl:15:19: executing "common.classes.hpa" at <include "annotations.labels" .>: error calling include: template: no template "annotations.labels" associated with template "gotpl"`

**Relevant Helm values:** ```autoscaling.enabled: true```

**What did you expect to happen:** minor upgrade

**Anything else you would like to add:** Looks like a simple typo. The other files are using `common.annotations` but [this line](https://github.com/k8s-at-home/library-charts/blame/70f1dd7648e1eb787c8b0060d890808aa9e42ee8/charts/stable/common/templates/classes/_HorizontalPodAutoscaler.tpl#L15=) is `annotations.labels`

**Additional Information:**

**Comment by gclawes** [comment]
Seeing this when installing `thelounge` with VPN enabled.

`Error: Failed to render chart: exit status 1: Error: template: thelounge/templates/common.yaml:1:3: executing "thelounge/templates/common.yaml" at <include "common.all" .>: error calling include: template: thelounge/charts/common/templates/_all.tpl:15:8: executing "common.all" at <include "common.addon.vpn" .>: error calling include: template: thelounge/charts/common/templates/addons/vpn/_vpn.tpl:16:20: executing "common.addon.vpn" at <include "common.addon.vpn.configmap" .>: error calling include: template: thelounge/charts/common/templates/addons/vpn/_configmap.tpl:12:19: executing "common.addon.vpn.configmap" at <include "annotations.labels" .>: error calling include: template: no template "annotations.labels" associated with template "gotpl"`

Values for `thelounge` (secrets omitted):
```yaml
# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: America/New_York
  WAIT_FOR_VPN: "true"

podAnnotations:
  sidecar.istio.io/inject: "true"

securityContext:
  runAsNonRoot: true
  runAsUser: 9000
  runAsGroup: 9000

command: ["sh"]
args: [ "-c", "source /shim/vpn.sh && /usr/local/bin/docker-entrypoint.sh thelounge start"]

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/enable-access-log: "true"
      cert-manager.io/issuer-group: certmanager.step.sm
      cert-manager.io/issuer-kind: StepClusterIssuer
      cert-manager.io/issuer: home-arpa
    hosts:
    - host: thelounge.k8s.home.arpa
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - secretName: thelounge-tls
      hosts:
        - thelounge.k8s.home.arpa

# -- Configure configMaps for the chart here.
# Additional configMaps can be added by adding a dictionary key similar to the 'config' object.
# @default -- See below
configmap:
  shim:
    # -- Enables or disables the configMap
    enabled: true
    # -- configMap data content. Helm template enabled.
    data:
      vpn.sh: |
        #!/usr/bin/env sh

        WAIT_FOR_VPN=${WAIT_FOR_VPN:-"false"}

        if
            [[ "${WAIT_FOR_VPN}" == "true" ]];
        then
            echo "Waiting for VPN to be connected..."
            while ! grep -s -q "connected" /shared/vpnstatus;
            do
                echo "VPN not connected"
                sleep 2
            done
            echo "VPN Connected, starting application..."
        fi

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: custom
    accessMode: ReadWriteOnce
    volumeSpec:
      nfs:
        server: nfs.home.arpa
        path: /tank/kubernetes/configs/thelounge
  shim:
    enabled: true
    type: configMap
    name: thelounge-shim
  shared:
    enabled: true
    type: emptyDir
    mountPath: /shared

addons:
  netshoot:
    enabled: false
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
  vpn:
    enabled: true
    type: openvpn
    openvpn:
      authSecret: thelounge
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    env:
      FIREWALL: 'on'
    scripts:
      # Commend out up.sh/down.sh so DNS doesn't get redirected
      up: |-
        #!/bin/bash
        #/etc/openvpn/up.sh
        echo "connected" > /shared/vpnstatus

      down: |-
        #!/bin/bash
        #/etc/openvpn/down.sh
        echo "disconnected" > /shared/vpnstatus
```
