### ISSUE TITLE
Secrets defined an array with a valuesFrom get a duplicate name

### ISSUE THREAD

**Issue by imle** [k8s-at-home/library-charts#161]
# Details

**Helm chart name and version:**

common 4.3.0

**What steps did you take and what happened:**

Setting the env to a list of variables instead of key-value pairs resulted in bad envvars.

**Relevant Helm values:**

```
env:
  - name: PG_USERNAME
    valueFrom:
      secretKeyRef:
        name: pg-credentials
        key: username
```

**What did you expect to happen:**

Correct env vars. 

**Additional Information:**

Resultant env section:
```
env:
- name: "PG_USERNAME"
  name: PG_USERNAME
  valueFrom:
    secretKeyRef:
      key: username
      name: pg-credentials
```
