### ISSUE TITLE
[common] Cannot deploy services with type ExternalName

### ISSUE THREAD

**Issue by danmanners** [k8s-at-home/library-charts#176]
# Description

I am unable to deploy ExternalName resources. They do not use a ports field, but without it the helm rendering fails.

## Expected Behavior

I should be able to deploy ExternalName service resources, which do not use ports.

## Helm Values to replicate

```yaml
service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        protocol: TCP
        port: 80
        targetPort: 3001
  extname:
    enabled: true
    type: ExternalName
    externalName: kube.danmanners.com
    annotations:
      external-dns.alpha.kubernetes.io/hostname: hostname
      external-dns.alpha.kubernetes.io/ttl: "300"
```

https://github.com/k8s-at-home/library-charts/blob/1b8b81ceb368e378c01aaf826142cfd948a93042/charts/stable/common/templates/classes/_service_ports.tpl#L12
