### ISSUE TITLE
[common] Ingresses can only refrence 1 service and port. 

### ISSUE THREAD

**Issue by rwaltr** [k8s-at-home/library-charts#31]
# Details

**Helm chart name:**

Common

**Describe the solution you'd like:**

Currently the commons is only able to reference a single service and port per ingress, you cannot define multiple paths with different ingresses per service. 

Ideally, this Syntax would be desirable

```
ingress:
  enabled: true
  hosts:
    - host: bw.domain.tdl
      paths:
        - path: /
          pathType: Prefix
        - path: /notifications/hub
          pathType: Prefix
          servicePort: 3012
```
with each path defaulting to service.port.port unless specified. 

**Anything else you would like to add:**

**Additional Information:**

[Discussion Context with @bjw-s](https://discord.com/channels/673534664354430999/750354840588386454/838460420498653264)
