### ISSUE TITLE
Error when setting lifecycle in value.yaml

### ISSUE THREAD

**Issue by nicholaswilde** [k8s-at-home/library-charts#44]
# Details

**Helm chart name and version:**

When trying to migrate [powerdns](https://github.com/k8s-at-home/charts/tree/671ff5362beddf7a14aca4d81313defb48ab9f12/charts/stable/powerdns) to common. I believe the following error will occur with any chart when setting `lifecycle`.

**What steps did you take and what happened:**

- Added `lifecycle` to `values.yaml`. Full input listed below.
- Ran `helm install powerdns . --dry-run`

**Relevant Helm values:**

```yaml
# values.yaml
...
lifecycle:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "let a=0; while [ $a -lt 200 ]; do sleep 5; let a=a+1; echo 'Attempt: '$a; if nc -vz powerdns-postgresql 5432; then pdnsutil list-zone mydomain.local 2>/dev/null && break; pdnsutil create-zone mydomain.local; fi; done"]
...
```

I get the following output.

```shell
$ helm install powerdns . --dry-run
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "postStart" in io.k8s.api.core.v1.Container
```

**What did you expect to happen:**

Generate the YAML output without any errors.

**Anything else you would like to add:**

Perhaps we need to change the indentation from 2 to 4? I haven't tested by updating the library.

https://github.com/k8s-at-home/library-charts/blob/2181868d20ac681d60beba5c5c2bebeaa5b741e2/charts/stable/common/templates/lib/controller/_container.tpl#L29-L30

**Additional Information:**

When using the following values, I get a valid output but `lifecycle` shows up twice.

```yaml
# values.yaml
lifecycle:
  lifecycle:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "let a=0; while [ $a -lt 200 ]; do sleep 5; let a=a+1; echo 'Attempt: '$a; if nc -vz powerdns-postgresql 5432; then pdnsutil list-zone mydomain.local 2>/dev/null && break; pdnsutil create-zone mydomain.local; fi; done"]
```

```shell
$ helm install powerdns . --dry-run
...
        lifecycle:
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - 'let a=0; while [ $a -lt 200 ]; do sleep 5; let a=a+1; echo ''Attempt: ''$a; if nc -vz powerdns-postgresql 5432; then pdnsutil list-zone mydomain.local 2>/dev/null && break; pdnsutil create-zone mydomain.local; fi
...
```
