### ISSUE TITLE
bad (main) service for codeserver addon when multiple ingress hosts

### ISSUE THREAD

**Issue by angelnu** [k8s-at-home/library-charts#64]
# Details

**Helm chart name and version:**
3.1.0

**What steps did you take and what happened:**
Used addon with multiple ingress entries
```
addons:
      codeserver:
        enabled: true
        volumeMounts:
        - name: config
          mountPath: /config
        ingress:
          enabled: true
          hosts:
          - host: ha-editor.pub.${CLUSTER_DOMAIN}
            paths:
            - path: /
              pathType: Prefix
          - host: ha-editor.home.${CLUSTER_DOMAIN}
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - ha-editor.pub.${CLUSTER_DOMAIN}
            - ha-editor.home.${CLUSTER_DOMAIN}
```

**Relevant Helm values:**

**What did you expect to happen:**

Both ingress entries pointing the vscode

**Anything else you would like to add:**

The problem comes from 
`{{- $_ := set (index (index $ingressValues.hosts 0).paths 0) "service" (dict "name" $svcName "port" .Values.addons.codeserver.service.ports.codeserver.port) -}}`

It should be a range statement to not only process the first entry.

**Additional Information:**

Easy to fix - can do a PR - capturing for now as issue to not forget it.
