### ISSUE TITLE
[common] ability to specify the `mountPropagation` key in a volumeMount entry in common library

### ISSUE THREAD

**Issue by thelastguardian** [k8s-at-home/library-charts#74]
# Details

**Helm chart name:**

common

**Describe the solution you'd like:**

Ability to specify the `mountPropagation` key in a volumeMount entry.

**Anything else you would like to add:**

Backstory: For some volumes, we need to specify `mountPropagation` in addition to mountPath, readOnly, subPath, etc. 

For example, an rclone container can mount a google drive or other remote into a shared emptyDir volume, and the other container (the main one from the helm chart, for example, sonarr, radarr, plex) should be able to see that sub-mount in that emptyDir volumeMount.

Referring to https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation, this usecase needs me to set `Bidirectional` mountPropagation for the custom/emptyDir volume on the rclone container (which I can do right now since the additionalContainers yaml is passed as-is to the rendered resource), but the volumeMount in the other main container still needs `mountPropagation` set to either `Bidirectional` or `HostToContainer`. This is currently not possible in the persistence/storage of the common-library since the template specifically sets the known-so-far keys (mountPath, subPath handling, readOnly).

The resulting volumeMount I want to be able to render is (assuming the example of plex):
```
      containers:
      - name: rclone # whole entry added as-is via additionalContainers yaml
        image: rclone/rclone:1.55
        args:
          - mount
          - "remote:location/media"
          - "/media/"
        volumeMounts:
        - name: rclone-shared-mount
          mountPath: /media
          mountPropagation: Bidirectional
      [...]
      - name: plex # rendered within helm chart
      [...]
        volumeMounts:
        - name: rclone-shared-mount
          mountPath: /media
          mountPropagation: HostToContainer # need to be able to specify this from the persistence.<name>.mountPropagation values
      volumes:
      - name: rclone-shared-mount # rendered from persistence.rclone-shared-mount.*
        emptyDir: {}
```

**Additional Information:**

This isn't limited to only emptyDir volumes specified inline/in-helm, since we should be able to mount an existngclaim PVC or a hostPath with a specified mountPropagation.

Adding something like
```
          {{- with $persistenceItem.mountPropagation }}
  mountPropagation: {{ . }}
          {{- end }}
```

to both sections of https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/templates/lib/controller/_volumemounts.tpl should do it.

Thanks!
