### ISSUE TITLE
[common] Support labeling or annotating PVCs

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/library-charts#80]
# Details

**Describe the solution you'd like:**

Add support to label and or annotate PVCs, e.g.

```yaml
persistence:
  config:
    metadata:
      labels:
        foo: bar
      annotations:
        bar: foo
```
