### ISSUE TITLE
No labels add in ingress

### ISSUE THREAD

**Issue by ElGranLoky** [k8s-at-home/library-charts#89]
# Details

Chart - Common
Versión: 4.0.0

**What steps did you take and what happened:**

Add labels in ingress.

```
ingress:
  main:
    enabled: true
    labels:
      foo: "var"
    nameOverride: local
    hosts:
      - host: example.k8
        paths:
          - path: /
            pathType: Prefix
```

**Relevant Helm values:**

https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/templates/classes/_ingress.tpl

```
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with $values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
``` 

**What did you expect to happen:**

Add labels in ingress after compile template

**Additional Information:**

No labels in yaml
